import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/nav/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "B-SmartLife",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen bg-slate-200`}>
        <nav /* className="z-10 sticky top-0" */>
          <Navbar />
        </nav>

        <main className="my-5 rounded-[50px] bg-white grow drop-shadow-lg overflow-hidden">
          {children}
        </main>

        <footer className="bg-green-200 p-10 rounded-t-[50px]">
          <p className="text-center">Footer</p>
        </footer>
      </body>
    </html>
  );
}
